name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GITHUB_PACKAGES_ACCESS_USER: ${{ secrets.GH_PACKAGES_ACCESS_USER }}
  GITHUB_PACKAGES_ACCESS_TOKEN: ${{ secrets.GH_PACKAGES_ACCESS_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Set up JDK with Dependency Caching
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'gradle'

      - name: Run check that gradle is capable to run
        run: ./gradlew help
